### ISSUE TITLE
Enforcing Conventions?

### ISSUE THREAD

**Issue by edblackburn** [derekgreer/nunit.specifications#1]
I am a fan of context specification and mspec too. I've got a hopelessly naive NUnit [Context Spec](https://github.com/blazey/blazey.features/blob/master/features.specs/context_specification.cs).

I'd like to make use of [nunit.specifications](https://github.com/derekgreer/nunit.specifications) and was wondering if I could make a couple of suggestions?

I have implemented test convention enforcement for a few clients using similar base classes.

Would you consider a PR for an extensible, opt-in mechanism for test enforcement?

Here are a few examples:

* Specification must has at least one assertion (It)
* Specification must have at least one or one and only one category attribute
* Specification name must match pattern i.e. must begin with "when_", all characters are lower case etc
* Specification asserts must match pattern i.e. must begin with "should_" etc

Here are a few implementation approaches:

* Hard code list of conventions in base class ctor to iterate and invoke (Attribute allows opt-outs)
* Use reflection to load all implementors of a given interface
* Abuse partial classes

I look forward to your thoughts.

Ed

**Comment by derekgreer** [comment]
Hey, Ed.  Thanks for your interest in Nunit.Specifications.

Concerning your suggestions, while I think these are perfectly sensible
style guidelines to follow, I wouldn't want NUnit.Specifications to impose
a specific set of naming conventions on people.  Some may prefer to name
their tests with an uppercase "When_" or have no need of categories which I
think are perfectly fine options.  Given the framework was conceived to
emulate MSpec, I don't think it should end up being more restrictive than
what you could do with MSpec.

With regard to your other email, NUnit.Specifications doesn't have a
dependency on Should, but it is used as part of it's own test suite.

Derek

**Comment by edblackburn** [comment]
Apologies for not paying more attention to when the Should reference is!

The conventions I mentioned were just suggestions of conventions that *could* be implemented. I have more than one client and they have different and conflicting conventions. Conventions are written by consumers of Nunit.Specifications and are not included, only the hook.

I'm sorry if I wasn't clear before, I was perhaps focusing too much on what a convention maybe.

If you're interested in a PR please let me know. I take no offence if you'd rather leave it.

Ed
