### ISSUE TITLE
Exceptions that occur in the establish are hidden by exceptions in the because

### ISSUE THREAD

**Issue by michael-shattuck** [derekgreer/nunit.specifications#10]
Essentially if an exception is thrown in the `Establish` it might subsequently cause an exception to be thrown in the `Because`. The current `ContextSpecification.cs` overwrites the exception that was stored by `InvokeEstablish` when calling `InvokeBecause`. This might hide the original exception.

**Comment by michael-shattuck** [comment]
See pull request #11

**Comment by derekgreer** [comment]
Fixed in v2.0.1.
