### ISSUE TITLE
Decouple assertion library

### ISSUE THREAD

**Issue by edblackburn** [derekgreer/nunit.specifications#2]
As per https://github.com/derekgreer/nunit.specifications/issues/1 may I suggest you remove the dependency of Should? One can easily reference if it your preferred assertion library?

My reasoning is because some of my clients prefer different assertion libraries and it's not clear why they need to be coupled.

**Comment by derekgreer** [comment]
NUnit.Specificatons doesn't have a dependency on the Should library.  it only uses it internally for it's own tests.
