### ISSUE TITLE
NUnit VS test runner not picking up tests in VS 2015 project

### ISSUE THREAD

**Issue by darrenhull** [derekgreer/nunit.specifications#4]
This test does not get picked up in vs 2015.

    [Component]
    public class MessageProcessorSpecs
    {

        [Category("component")]
        public class MessageProcessorSpecs1 : ContextSpecification
        {
                       
            public class when_a_message_is_empty
            {
                static bool _result;

                Establish context = () =>
                {
                    _result = true;
            };

                Because of = () =>
                {
                    _result = true;
                };

                It it_should_return_false = () => _result.ShouldBeFalse();
            }
        }
    }

**Comment by derekgreer** [comment]
This sounds like an issue with the NUnit Test Adapter for VS 2015.  Perhaps the new version doesn't respect the full NUnit API with respect to how tests may be defined.  If that's the case, I'm afraid all I'd be able to do is recommend using another test runner such as Resharper, Test-Driven.Net, or the stand alone NUnit Test Runner.

**Comment by mickdelaney** [comment]
Same issue for me with Resharper 10 & TestDriven.net in 2015 
It runs in the nunit GUI tool but I cant debug any tests in vs2015.

**Comment by derekgreer** [comment]
Unfortunately I don't have Resharper 10 to test with, but I did just create a test with Visual Studio 2015 + Resharper 9.2 and NUnit.Specifications is working as expected.

**Comment by derekgreer** [comment]
I was also able to create a working example with Visual Studio 2015 + TestDriven.NET-3.9.2905	RTM.

**Comment by mickdelaney** [comment]
i rolled back to R# 9. :-)

**Comment by derekgreer** [comment]
I'm not sure what this issue originally pertained to (e.g. VS TestRunner, Resharper, TDD.Net, etc.), but I'm going to go ahead and close this as any failure to recognize tests will be a byproduct of a particular test runner's support of the targeted version of NUnit.
