### ISSUE TITLE
Use with NUnit 3.0

### ISSUE THREAD

**Issue by vidarkongsli** [derekgreer/nunit.specifications#5]
Is there any plans to support using this library with NUnit 3?

**Comment by mickdelaney** [comment]
I've started a discussion on this with the nunit team. 

https://groups.google.com/forum/#!topic/nunit-discuss/Neb5OFGAnyo

been looking at changing it myself. hopefully can come up with a solution soon

**Comment by mickdelaney** [comment]
derek, judging from the forum it looks like you have a strategy on 3x support. is this the case  ???

**Comment by derekgreer** [comment]
I just posted to that thread.  I made a bit of progress with my custom
SpecificationSourceAttribute,
but unfortunately there were still some issues and I haven't had time to do
further testing.

**Comment by derekgreer** [comment]
New version published: [NUnit.Specifications.NUnit3](https://www.nuget.org/packages/NUnit.Specifications.NUnit3/)
