### ISSUE TITLE
Setup/Act/Assert Delegates

### ISSUE THREAD

**Issue by adamfisher** [derekgreer/nunit.specifications#6]
Thanks for creating this library. It has been really useful coming from Mspec. I was wondering if it would be possible to add attributes to the library to support custom names for the steps so I could do something like this to match gherkin syntax:

``` csharp
    [SetupDelegate]
    public delegate void Given();

    [ActDelegate]
    public delegate void When();

    [AssertDelegate]
    public delegate void Then();
```

I didn't see the types anywhere in the Machine.Specifications library which I thought is where they would have come from.

**Comment by derekgreer** [comment]
NUnit.Specifications is a context/specification wrapper around NUnit.  It does not support Gherkin style grammar and I have no plans to overload purpose to support this style.  If you're really looking for this style, my recommendation would be to checkout the [SpecsFor](http://specsfor.com/) project.
