### ISSUE TITLE
It don't *think* there's a core CLR nuget package... is there likely to be one?

### ISSUE THREAD

**Issue by penderi** [derekgreer/nunit.specifications#7]
Hi,

I'm anxious to try nunit.specs on a core CLR project. nUnit has core CLR support, so is it likely this will be ported too??

**Comment by penderi** [comment]
Or, more helpfully, I've a coreCLR version of nUnit3. I'll fork and issue a PR.

**Comment by derekgreer** [comment]
Yes, NUnit.Specifications support for .Net Core is planned.

**Comment by penderi** [comment]
Would you accept a PR for NUnit3 on coreCLR?

**Comment by penderi** [comment]
Just in case, I've sent a PR. It worked out rather tidily (I think)
https://github.com/derekgreer/nunit.specifications/pull/8

**Comment by derekgreer** [comment]
NUnit.Specifications now supports the core CLR as of version 2.0.0.  See the documentation for details on how to get this up and going.
