### ISSUE TITLE
nunit.specifications.nunit3 not working with Resharper 2016.2.2

### ISSUE THREAD

**Issue by SlyNet** [derekgreer/nunit.specifications#9]
This simple spec 

```
    [Component]
    public class test : ContextSpecification
    {
        Establish context = () =>
        {
            field = "test";
        };

        Because of = () => field = "test1";

        It should_change_field = () => field.Should().Be("test");

        static string field;
    }
```

Produces nothing it the test runner output window. 
Target .net framework 4.6.2
NUnit version 3.4.1
NUnit.Specifications.NUnit3 version 1.1.2

**Comment by Cesar-Ofi** [comment]
Same here, not working with R# 2016.2.3
Did you found any solution?
Thanks

**Comment by derekgreer** [comment]
Whether any given test runner supports NUnit.Specifications is contingent upon the level of support it has for the full NUnit API.  NUnit.Specifications utilizes NUnit's ```ITestBuilder``` interface to dynamically find tests.  In some cases a given version of a test runner or adapter does not fully support this.  For example, for the latest version of NUnit's own test adapter for the VSTest runner, it properly recognizes projects which contain only tests created using ITestBuilder interface for projects targeting netcoreapp1.1, but it only recognizes these tests for projects targeting 4.6.2 which contain at least one class it recognizes as a traditional NUnit test.

Unfortunately, the NUnit.Specifications library can't control the degree to which test runners support NUnit's dynamic test discovery capabilities.  As such, I don't see there's anything I can do on my end.
